{% set name = "deepEMhancer" %}
{% set version = "0.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: "../"
#  git_rev: "master"
#  git_url: "https://github.com/rsanchezgarc/deepEMhancer/"

build:
  number: 0
  entry_points:
    - deepemhancer=deepEMhancer.exeDeepEMhancer:commanLineFun
  script: "{{ PYTHON }} -m pip install . -vv --no-deps && echo 'DONE' "

requirements:
  build:
    - numpy >=1.24,<2.0
    - setuptools
    - joblib >=1.4
    - mrcfile >=1.4
    - pip
    - python >=3.12,<3.13
    - requests >=2.32
    - scikit-image >=0.22
    - scipy >=1.14
    - tensorflow[and-cuda] >=2.18
    - tqdm >=4.66
    - h5py * nompi*
    - flatbuffers
  run:
    - numpy >=1.24,<2.0
    - setuptools
    - joblib >=1.4
    - mrcfile >=1.4
    - pip
    - python >=3.12,<3.13
    - requests >=2.32
    - scikit-image >=0.22
    - scipy >=1.14
    - tensorflow[and-cuda] >=2.18
    - tqdm >=4.66
    - h5py * nompi*
    - flatbuffers
test:
  imports:
    - deepEMhancer
    - deepEMhancer.applyProcessVol
    - deepEMhancer.utils
  commands:
    - deepemhancer --help
    - python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

about:
  home: "https://github.com/rsanchezgarc/deepEMhancer"
  license: Apache 2.0
  license_family: APACHE
  license_file:
  summary: "Deep learning for cryo-EM maps post-processing"
  doc_url:
  dev_url:
